<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{Axes and legends}
-->
  
# Guides: Axes and legends

When polishing graphics for production you often spend a lot of time getting the
axes and legends looking exactly right. This vignette describes the ggvis 
functions that allow you to control plot guides: axes and legends.

In gigvis, axes and legends are related to scales, but are described separately.
This is different to ggplot2, where the scale objects controlled both the
details of the mapping and how it should be displayed on the plot. This makes
gigvis a little more verbose, but it also makes it more flexible.

Currently, ggvis guides are a close map to their vega equivalents. For 
reference, you may also want to read the vega documentation for the 
underlying [axis](https://github.com/trifacta/vega/wiki/Axes) and 
[legend](https://github.com/trifacta/vega/wiki/Legends) components.

## Common properties

Axes and legends have relatively few components in common, but the ones that
they share are particularly important.

* `scale` (axis), and stroke/fill/size/shape (legend) describe which scale (or 
  scales in the case of a legend) will be displayed on the guide
  
  ```R
  guide_axis("x")
  guide_axis("y")
  guide_legend(fill = stroke)
  guide_legend(size = size)
  # Display multiple scales in one legend:
  guide_legend(fill = stroke, size = size)
  ```
  
* `title`, a string describing the guide

  ```R
  guide_axis("x", title = "My x variable")
  guide_legend(fill = fill, title = "Some interesting colours")
  ```

* `values`, used to override the default placement of ticks on an axis or gradient
  legend, or visible legend labels. 
  
* `format`, a d3 [formatting specification](https://github.com/mbostock/d3/wiki/Formatting)
  that controls how values are converted to strings. 
  
### Custom styles

Finally, both axes and legends share `properties`, which is a named list of 
`props()` that is applied to specified components of the axis or legend. For
axes, you can set the properties of the ticks (or majorTicks and minorTicks 
separately), the labels and axis. For legends, you can set properties of the 
title, label, symbols (for categorical scales), gradient (for continuous 
scales), and legend.

Currently, if you're using mulitple scales, you'll need to properties to make
sure that your legends don't overlap.

```R
ggvis(mtcars, props(x ~ wt, y ~ mpg), 
  mark_symbol(),
  guide_axis("x", properties = list(
    axis = props(stroke = "red", strokeWidth = 5),
    grid = props(stroke = "blue"),
    ticks = props(stroke = "blue", strokeWidth = 2),
    labels = props(angle = 45, align = "left", fontSize = 20)
  ))
)
```

  
## Axis

```R
ggvis(mtcars, props(x ~ wt, y ~ mpg), mark_symbol())

ggvis(mtcars, props(x ~ wt, y ~ mpg), mark_symbol(),
  guide_axis("x", title = "Weight"),
  guide_axis("y", title = "Miles per gallon"))

# Use title offset to push the titles further away
ggvis(mtcars, props(x ~ wt, y ~ mpg), mark_symbol(),
  guide_axis("x", title = "Weight", title_offset = 50),
  guide_axis("y", title = "Miles per gallon", title_offset = 50))
  
```

### Tick sizes and padding

There are five options that control the appearance of ticks:

* `subdivide`: the number of minor ticks between each major tick.

* `tick_padding`: the padding between ticks and labels (in pixels)

* `tick_size_major`, `tick_size_minor` ,`tick_size_end`: the size of the
  major, minor and end ticks. By default they are all the same size as the major
  ticks, but you can set them separately.

```R
# Change ticks and subdivide with minor ticks
ggvis(mtcars, props(x ~ wt, y ~ mpg), mark_symbol(), 
  guide_axis("x", subdivide = 9, values = 1:6),
  guide_axis("y", subdivide = 1, values = seq(10, 34, by = 2))
)

# Make the minor ticks smaller and the end ticks longer
ggvis(mtcars, props(x ~ wt, y ~ mpg), mark_symbol(), 
  guide_axis("x", subdivide = 9, values = 1:6, tick_size_major = 10, 
    tick_size_minor = 5, tick_size_end = 15, tick_padding = 20)
)
```

### Orientation

You can control the placement of the axes with the `orient` argument:

```R
ggvis(mtcars, props(x ~ wt, y ~ mpg), mark_symbol(), 
  guide_axis("x", orient = "top"),
  guide_axis("y", orient = "right")
)
```

If you want axes on both sides, just add two axes:

```R
ggvis(mtcars, props(x ~ wt, y ~ mpg), mark_symbol(), 
  guide_axis("x", orient = "bottom"),
  guide_axis("x", orient = "top")
)
```

You can even put multiple scales on one side:

```R
ggvis(mtcars, props(x ~ wt, y ~ mpg), mark_symbol(), 
  guide_axis("x"),
  guide_axis("x", offset = 40, grid = FALSE)
)
```

This is probably more useful if you have multiple x or y position scales, but 
I've already discussed that enough times in these vignettes given how much I 
dislike them.


## Legends


### Combining legends 

Unlike ggplot2, by default, ggvis will not combine scales based on the same 
underlying variables into a single legend. Instead you must do this yourself
by supplying the name of multiple scales to one legend:
  
```R
mtcars$cyl <- ordered(mtcars$cyl)
ggvis(mtcars, props(x ~ mpg, y ~ wt, size ~ cyl, fill ~ cyl), 
  mark_symbol())
ggvis(mtcars, props(x ~ mpg, y ~ wt, size ~ cyl, fill ~ cyl), 
  mark_symbol(),
  guide_legend(size = "size", fill = "fill"))
```
